---
AWSTemplateFormatVersion: '2010-09-09'
Description: MSSQL RDS Instance Provision
Outputs:
  mssqlurl:
    Description: Output MSSQL Endpoint
    Value:
      Fn::GetAtt:
      - DBInstance
      - Endpoint.Address
Parameters:
  DBInstanceClass:
    Default: db.r4.large
    Description: Instance type
    Type: String
  DBInstanceName:
    Default: UATSqlRdsDB-01
    Description: Database instance identifier
    Type: String
  DBPassword:
    ConstraintDescription: must contain only alphanumeric characters.
    Default: Eixgl0bal123
    Description: The database admin account password
    NoEcho: 'true'
    Type: String
  DBUser:
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
    Default: eixglobaldb
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    NoEcho: 'true'
    Type: String
  Storage:
    Default: '100'
    Description: Storage Size of MSSQL RDS Instance
    Type: String
  Subnet1:
    Default: subnet-03be7b267c5157e78
    Description: Private Subnet1
    Type: String
  Subnet2:
    Default: subnet-0ddb17d1d4834da69
    Description: Private Subnet2
    Type: String
  VPC:
    Default: vpc-09c973258559c9545
    Description: VPC Id where the servers will be deployed
    Type: String
Resources:
  DBInstance:
    DeletionPolicy: Snapshot
    Properties:
      AllocatedStorage:
        Ref: Storage
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      BackupRetentionPeriod: '3'
      DBInstanceClass:
        Ref: DBInstanceClass
      DBInstanceIdentifier:
        Ref: DBInstanceName
      DBSubnetGroupName:
        Ref: myDBSubnetGroup
      Engine: sqlserver-se
      EngineVersion: 14.00.3049.1.v1
      MultiAZ: true
      LicenseModel: license-included
      MasterUserPassword:
        Ref: DBPassword
      MasterUsername:
        Ref: DBUser
      PreferredBackupWindow: 01:00-03:00
      PreferredMaintenanceWindow: sun:06:00-sun:06:30
      PubliclyAccessible: 'true'
      StorageEncrypted: 'false'
      StorageType: gp2
      VPCSecurityGroups:
      - Ref: SecurityGroup
    Type: AWS::RDS::DBInstance
  SecurityGroup:
    Properties:
      GroupDescription: Enable access on Internal Network
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        FromPort: '0'
        IpProtocol: "-1"
        ToPort: '65535'
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/16
        FromPort: '0'
        IpProtocol: "-1"
        ToPort: '65535'
      - CidrIp: 178.255.66.4/32
        FromPort: '0'
        IpProtocol: "-1"
        ToPort: '65535'      
      VpcId:
        Ref: VPC
    Type: AWS::EC2::SecurityGroup
  myDBSubnetGroup:
    Properties:
      DBSubnetGroupDescription: DB Subnet Group
      SubnetIds:
      - Ref: Subnet1
      - Ref: Subnet2
    Type: AWS::RDS::DBSubnetGroup