AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to launch a Windows Bastion Servers
Parameters:
  AMI:
    Description: AMI ID
    Type: 'AWS::EC2::Image::Id'
    Default: ami-08a60203431f22e65
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VpcId of your existing Virtual Private Cloud (VPC).
    Default: vpc-09c973258559c9545
  PublicSubnetA:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-056594e5a5e193cf9
    Description: The list of SubnetIds where the stack will be launched  
  PublicSubnetB:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-02e3309be6c87f183
    Description: The list of SubnetIds where the stack will be launched  
  SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: sg-0f737cb47351fd063
    Description: The security groups allowed to access these servers
  InstanceType:
    Description: Type of EC2 instance to launch.
    Type: String
    Default: c4.large
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c1.xlarge
      - c4.large
      - c5.4xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  Country:
    Description: Country code for stack.
    Type: String
  KeyName:
    Description: TheEC2 KeyPair to allow RemoteDesktop access or SSH to the instances.
    Type: String
    Default: ec2connect
Resources:
  WEBRES01:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName:
        Ref: KeyName
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile: uatservicesrole
      ImageId:
        Ref: AMI
      NetworkInterfaces:
        - DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId:
            Ref: PublicSubnetB
          GroupSet:
            Ref: SecurityGroups
      Tags:
        - Key: Name
          Value: EUUATSSIS-01
        - Key: Team-Role
          Value: Platform-Web
        - Key: Division
          Value: Core
        - Key: Country
          Value:
            Ref: Country  
Outputs:
  WEBRES01:
    Value:
      Ref: WEBRES01
