AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to launch a Web Resources Servers
Parameters:
  AMI:
    Description: AMI ID
    Type: 'AWS::EC2::Image::Id'
    Default: ami-07683a44e80cd32c5
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: VpcId of your existing Virtual Private Cloud (VPC).
    Default: vpc-09c973258559c9545
  PublicSubnetA:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-056594e5a5e193cf9
    Description: The list of SubnetIds where the stack will be launched
  PrivateSubnetA:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-03be7b267c5157e78
    Description: The list of SubnetIds where the stack will be launched
  PublicSubnetB:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-02e3309be6c87f183
    Description: The list of SubnetIds where the stack will be launched
  PrivateSubnetB:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-0ddb17d1d4834da69
    Description: The list of SubnetIds where the stack will be launched
  SecurityGroups:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Default: sg-096679777eb52e324
    Description: The security groups allowed to access these servers
  InstanceType:
    Description: Type of EC2 instance to launch.
    Type: String
    Default: c5.4xlarge
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c1.xlarge
      - c5.4xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  Country:
    Description: Country code for stack.
    Type: String
  KeyName:
    Description: TheEC2 KeyPair to allow RemoteDesktop access or SSH to the instances.
    Type: String
    Default: ec2connect
Resources:
  WEBRES01:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName:
        Ref: KeyName
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile: uatservicesrole
      ImageId:
        Ref: AMI
      NetworkInterfaces:
        - DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId:
            Ref: PrivateSubnetA
          GroupSet:
            Ref: SecurityGroups
      Tags:
        - Key: Name
          Value: UATWEB
        - Key: Team-Role
          Value: Platform-Web
        - Key: Division
          Value: Core
        - Key: Country
          Value:
            Ref: Country
  WEBRESELB:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      Subnets:
        - Ref: PublicSubnetA
        - Ref: PublicSubnetB
      SecurityGroups:
        Ref: SecurityGroups
      Tags:
        - Key: Name
          Value: UATWEBLB
        - Key: Team-Role
          Value: Platform-Web
        - Key: Division
          Value: Core
        - Key: Country
          Value:
            Ref: Country
      Instances:
        - Ref: WEBRES01
      Listeners:
        - LoadBalancerPort: '443'
          InstancePort: '443'
          Protocol: TCP
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      HealthCheck:
        Target: 'HTTP:80/index.html'
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '35'
        Timeout: '10'
Outputs:
  WEBRES01:
    Value:
      Ref: WEBRES01
  WEBRESELB:
    Value:
      Ref: WEBRESELB